In [7]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

from keras.models import Sequential
from keras.layers import Dense

In [9]:
data = pd.read_csv("boston.csv")
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [10]:
print(data.isnull().sum())

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [11]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [12]:
data.tail()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [16]:
X = data[['LSTAT', 'RM', 'PTRATIO']]
y = data['MEDV']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)

LinearRegression()

In [20]:
y_pred_lr = lr_model.predict(X_test_scaled)

mse_lr = mean_squared_error(y_test, y_pred_lr)
mae_lr = mean_absolute_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print("Linear Regression Evaluation")
print("MSE:", mse_lr)
print("MAE:", mae_lr)
print("R2 Score:", r2_lr)

Linear Regression Evaluation
MSE: 27.114957415580566
MAE: 3.3325380783240965
R2 Score: 0.6302528487272829

In [21]:
dnn_model = Sequential()

dnn_model.add(Dense(128, activation='relu', input_dim=3))
dnn_model.add(Dense(64, activation='relu'))
dnn_model.add(Dense(32, activation='relu'))
dnn_model.add(Dense(16, activation='relu'))
dnn_model.add(Dense(1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
dnn_model.compile(optimizer='adam',loss='mse',metrics=['mae'])

In [23]:
history = dnn_model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.05,verbose=1)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 5s 45ms/step - loss: 581.3107 - mae: 22.1802 - val_loss: 476.9095 - val_mae: 20.2644
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 510.5661 - mae: 20.5175 - val_loss: 392.1833 - val_mae: 17.9963
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 376.8747 - mae: 17.1830 - val_loss: 244.5032 - val_mae: 13.0872
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 186.3622 - mae: 11.5903 - val_loss: 98.9196 - val_mae: 7.2194
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 74.0647 - mae: 6.6869 - val_loss: 74.7693 - val_mae: 5.9718
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 49.4001 - mae: 5.3338 - val_loss: 77.3553 - val_mae: 5.8873
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 37.0292 - mae: 4.6064 - val_loss: 73.2579 - val_mae: 5.6663
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32.2911 - mae: 4.2469 - val_loss: 67.2042 - val_mae: 5.4033
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30.0633 - mae: 4.1068 - val_loss: 66.1387 - val_mae: 5.3297
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 28.9202 - mae: 4.0524 - val_loss: 64.8847 - val_mae: 5.2522
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.3929 - mae: 3.9306 - val_loss: 65.8664 - val_mae: 5.2693
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.5883 - mae: 3.8544 - val_loss: 64.6451 - val_mae: 5.2730
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.6828 - mae: 3.7953 - val_loss: 63.2667 - val_mae: 5.1561
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24.7177 - mae: 3.7236 - val_loss: 62.4258 - val_mae: 5.0714
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.8232 - mae: 3.6612 - val_loss: 62.0857 - val_mae: 5.0331
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.1851 - mae: 3.6159 - val_loss: 61.7706 - val_mae: 4.9640
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.3377 - mae: 3.5268 - val_loss: 61.8342 - val_mae: 4.9353
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.8769 - mae: 3.5134 - val_loss: 60.4189 - val_mae: 4.8334
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.1132 - mae: 3.4387 - val_loss: 59.4532 - val_mae: 4.7043
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.7222 - mae: 3.3889 - val_loss: 59.9487 - val_mae: 4.7343
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 20.2175 - mae: 3.3703 - val_loss: 60.2066 - val_mae: 4.6961
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.4905 - mae: 3.2966 - val_loss: 58.3722 - val_mae: 4.5914
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 19.1656 - mae: 3.2788 - val_loss: 59.8626 - val_mae: 4.5537
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.8175 - mae: 3.2198 - val_loss: 57.0405 - val_mae: 4.4766
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.2852 - mae: 3.2046 - val_loss: 58.1138 - val_mae: 4.4857
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.1639 - mae: 3.1290 - val_loss: 58.3891 - val_mae: 4.4200
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 17.7080 - mae: 3.1333 - val_loss: 56.4156 - val_mae: 4.3228
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 17.3660 - mae: 3.0872 - val_loss: 56.4241 - val_mae: 4.2698
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 17.0304 - mae: 3.0438 - val_loss: 57.3899 - val_mae: 4.3663
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 17.0751 - mae: 3.0511 - val_loss: 55.9896 - val_mae: 4.1888
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 16.4836 - mae: 2.9957 - val_loss: 56.2241 - val_mae: 4.3098
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 16.3697 - mae: 2.9656 - val_loss: 56.9470 - val_mae: 4.1391
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.3036 - mae: 2.9814 - val_loss: 54.0485 - val_mae: 4.0554
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.8404 - mae: 2.8788 - val_loss: 56.0618 - val_mae: 4.0970
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.6715 - mae: 2.9094 - val_loss: 54.1212 - val_mae: 3.9934
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.3118 - mae: 2.8445 - val_loss: 54.0205 - val_mae: 3.9939
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 15.2887 - mae: 2.8620 - val_loss: 55.5486 - val_mae: 4.0893
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.1848 - mae: 2.8080 - val_loss: 52.8360 - val_mae: 3.9953
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.0972 - mae: 2.8231 - val_loss: 55.5466 - val_mae: 4.0462
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.9919 - mae: 2.7996 - val_loss: 53.7944 - val_mae: 3.9994
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.7063 - mae: 2.7926 - val_loss: 52.8601 - val_mae: 3.8837
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.6196 - mae: 2.7373 - val_loss: 53.9425 - val_mae: 4.0015
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.5915 - mae: 2.7835 - val_loss: 53.1303 - val_mae: 3.9302
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.3684 - mae: 2.7319 - val_loss: 52.9264 - val_mae: 3.9163
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.1332 - mae: 2.6935 - val_loss: 53.3790 - val_mae: 3.9786
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.4017 - mae: 2.7331 - val_loss: 52.0342 - val_mae: 3.8581
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.3533 - mae: 2.7285 - val_loss: 54.0872 - val_mae: 4.0253
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.1684 - mae: 2.7183 - val_loss: 51.4289 - val_mae: 3.8107
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.8022 - mae: 2.6855 - val_loss: 53.7164 - val_mae: 4.0188
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.0410 - mae: 2.7039 - val_loss: 51.7915 - val_mae: 3.8500
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.6555 - mae: 2.6641 - val_loss: 53.0525 - val_mae: 3.9238
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.6585 - mae: 2.6522 - val_loss: 50.8831 - val_mae: 3.8324
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.7766 - mae: 2.6799 - val_loss: 53.6106 - val_mae: 3.9294
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.7877 - mae: 2.6609 - val_loss: 51.3278 - val_mae: 3.8624
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.4179 - mae: 2.6521 - val_loss: 53.8552 - val_mae: 4.0100
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.6883 - mae: 2.6652 - val_loss: 51.3274 - val_mae: 3.8375
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.4920 - mae: 2.6447 - val_loss: 52.5478 - val_mae: 3.9177
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.4230 - mae: 2.6140 - val_loss: 52.9080 - val_mae: 3.9159
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.2540 - mae: 2.5900 - val_loss: 52.6423 - val_mae: 3.9145
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.3850 - mae: 2.6320 - val_loss: 52.0316 - val_mae: 3.8626
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.1332 - mae: 2.5948 - val_loss: 52.0989 - val_mae: 3.8802
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.5935 - mae: 2.6853 - val_loss: 55.1557 - val_mae: 4.1275
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.4431 - mae: 2.6291 - val_loss: 50.0023 - val_mae: 3.7417
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.1454 - mae: 2.6027 - val_loss: 52.7486 - val_mae: 3.9273
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.1546 - mae: 2.6226 - val_loss: 51.5947 - val_mae: 3.8342
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.2064 - mae: 2.6056 - val_loss: 51.7697 - val_mae: 3.8385
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.0082 - mae: 2.5935 - val_loss: 51.6800 - val_mae: 3.8871
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.9510 - mae: 2.5846 - val_loss: 50.4117 - val_mae: 3.7682
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.3667 - mae: 2.6100 - val_loss: 51.1754 - val_mae: 3.8555
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.1086 - mae: 2.6627 - val_loss: 53.3849 - val_mae: 3.9642
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.3939 - mae: 2.6603 - val_loss: 50.3249 - val_mae: 3.8093
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.9812 - mae: 2.6009 - val_loss: 52.1371 - val_mae: 3.9333
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.8877 - mae: 2.5915 - val_loss: 51.3446 - val_mae: 3.8017
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.7128 - mae: 2.5757 - val_loss: 51.3539 - val_mae: 3.8687
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.6471 - mae: 2.5644 - val_loss: 51.6461 - val_mae: 3.8487
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 12.6103 - mae: 2.5674 - val_loss: 52.1756 - val_mae: 3.8619
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 12.7052 - mae: 2.5606 - val_loss: 51.8301 - val_mae: 3.8587
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.9182 - mae: 2.5843 - val_loss: 50.3846 - val_mae: 3.8369
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.4887 - mae: 2.6057 - val_loss: 53.0809 - val_mae: 3.9533
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.9430 - mae: 2.6387 - val_loss: 50.7075 - val_mae: 3.9687
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 12.6079 - mae: 2.5980 - val_loss: 52.9671 - val_mae: 3.9071
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 12.3301 - mae: 2.5143 - val_loss: 49.8128 - val_mae: 3.7486
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 13.2372 - mae: 2.6356 - val_loss: 54.4629 - val_mae: 4.0917
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.6356 - mae: 2.6038 - val_loss: 51.3444 - val_mae: 3.8727
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.5240 - mae: 2.6275 - val_loss: 55.6642 - val_mae: 4.1882
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 12.8521 - mae: 2.5893 - val_loss: 48.6900 - val_mae: 3.8172
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 12.9083 - mae: 2.6055 - val_loss: 56.4648 - val_mae: 4.2462
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.8248 - mae: 2.6062 - val_loss: 50.2508 - val_mae: 3.6880
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 12.3574 - mae: 2.5300 - val_loss: 51.8806 - val_mae: 3.9090
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.2538 - mae: 2.5830 - val_loss: 51.0199 - val_mae: 3.7584
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.7798 - mae: 2.5713 - val_loss: 50.6708 - val_mae: 3.8555
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 12.4404 - mae: 2.5398 - val_loss: 50.6539 - val_mae: 3.7848
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 12.7759 - mae: 2.6055 - val_loss: 51.7699 - val_mae: 3.8778
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 12.5042 - mae: 2.6124 - val_loss: 53.4751 - val_mae: 4.0230
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.1756 - mae: 2.5309 - val_loss: 51.3491 - val_mae: 3.8993
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.2936 - mae: 2.5341 - val_loss: 50.0661 - val_mae: 3.8076
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 12.4578 - mae: 2.5551 - val_loss: 51.3279 - val_mae: 3.9106
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 12.0577 - mae: 2.5563 - val_loss: 52.7972 - val_mae: 3.9766
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.3767 - mae: 2.5517 - val_loss: 50.7763 - val_mae: 3.8882
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 11.9228 - mae: 2.5032 - val_loss: 52.1870 - val_mae: 3.9272

In [24]:
y_pred_dnn = dnn_model.predict(X_test_scaled)

mse_dnn = mean_squared_error(y_test, y_pred_dnn)
mae_dnn = mean_absolute_error(y_test, y_pred_dnn)
r2_dnn = r2_score(y_test, y_pred_dnn)

print("\nDeep Neural Network Evaluation")
print("MSE:", mse_dnn)
print("MAE:", mae_dnn)
print("R2 Score:", r2_dnn)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

Deep Neural Network Evaluation
MSE: 15.641120399821018
MAE: 2.338251428043141
R2 Score: 0.7867133028494349

In [25]:
new_data = np.array([[0.1, 10.0, 5.0]])
new_data_scaled = scaler.transform(new_data)

prediction = dnn_model.predict(new_data_scaled)
print("Predicted House Price:", prediction[0][0], "thousand dollars")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Predicted House Price: 76.99757 thousand dollars

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(